PREFIX a: <http://www.daml.org/2001/01/gedcom/gedcom#>

SELECT DISTINCT ?name 
WHERE {
		{
		?x a:name ?name .
		FILTER regex(?name, "Beatrix")
		}
		UNION
		{
		?x a:name ?name .
		FILTER regex(?name, "Beatrice")
		}
	 
	   }