PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?local ?remote ?remote_property ?remote_value
WHERE {
    ?local owl:sameAs ?remote .
    SERVICE <http://dbpedia.org/sparql> {
        ?remote ?remote_property ?remote_value
    }
}